// This is an autogenerated file from Firebase Studio.
import {initializeApp, getApp, getApps} from 'firebase/app';
import {getFirestore} from 'firebase/firestore';
import { getAuth, signOut } from "firebase/auth";

const firebaseConfig = {
  apiKey: "AIzaSyA7mj7C7c3lHxf7Gt2maev0qC49VBjfdmA",
  authDomain: "medfriend-70e0e.firebaseapp.com",
  projectId: "medfriend-70e0e",
  storageBucket: "medfriend-70e0e.firebasestorage.app",
  messagingSenderId: "1087779369594",
  appId: "1:1087779369594:web:c7c6d597f1562a9f2381c3",
  measurementId: "G-RQB0CFKMFD"
};

// Initialize Firebase
const app = !getApps().length ? initializeApp(firebaseConfig) : getApp();
const db = getFirestore(app);
const auth = getAuth(app);

const logout = () => signOut(auth);

export {app, db, auth, logout};
